# Generated by Django 3.1.5 on 2021-01-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210121_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date_start',
        ),
    ]
