# Generated by Django 3.1.5 on 2021-01-21 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210121_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='poll',
            name='date_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
