# Generated by Django 3.1.5 on 2021-01-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210121_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date_start',
        ),
    ]
